// 55+ SMART challenges for executives in all languages
export const challenges = {
  ro: [
    { id: 1, title: "10km Mâine", description: "Aleargă 10km într-un ritm confortabil mâine dimineață. Finalizează între 60-75 min.", difficulty: "medium", timeframe: "1 zi", category: "running" },
    { id: 2, title: "Semi-Maraton în 6 Luni", description: "Pregătește-te pentru un semi-maraton (21.1km) în următoarele 6 luni. Target: sub 2h 15min.", difficulty: "hard", timeframe: "6 luni", category: "running" },
    { id: 3, title: "100 Flotări Zilnic", description: "Fă 100 flotări pe zi timp de 30 zile. Poți împărți în seturi de 20-25.", difficulty: "medium", timeframe: "30 zile", category: "strength" },
    { id: 4, title: "5km Sub 25 min", description: "Atingi un 5km sub 25 minute în următoarele 8 săptămâni.", difficulty: "medium", timeframe: "8 săptămâni", category: "running" },
    { id: 5, title: "Maraton în 12 Luni", description: "Pregătire completă pentru maraton (42.2km). Target: finalizare sub 4h 30min.", difficulty: "hard", timeframe: "12 luni", category: "running" },
    { id: 6, title: "Pierde 5kg în 90 Zile", description: "Scade 5kg grăsime corporală prin running, forță și nutriție optimizată.", difficulty: "medium", timeframe: "90 zile", category: "nutrition" },
    { id: 7, title: "30 Zile Fără Zahăr", description: "Elimină complet zahărul adăugat timp de 30 zile. Energie susținută garantată.", difficulty: "medium", timeframe: "30 zile", category: "nutrition" },
    { id: 8, title: "3 Antrenamente/Săptămână", description: "Menține consistența: 3 antrenamente (2 running + 1 strength) săptămânal, 12 săptămâni.", difficulty: "easy", timeframe: "12 săptămâni", category: "habit" },
    { id: 9, title: "Ridică 100kg Deadlift", description: "Ajunge la deadlift de 100kg cu formă perfectă în 16 săptămâni.", difficulty: "hard", timeframe: "16 săptămâni", category: "strength" },
    { id: 10, title: "10.000 Pași Zilnic", description: "10.000 pași în fiecare zi timp de 60 zile. Folosește pauzele de masă.", difficulty: "easy", timeframe: "60 zile", category: "movement" },
    { id: 11, title: "Trail Run 15km", description: "Finalizează un trail run de 15km în munte în următoarele 10 săptămâni.", difficulty: "hard", timeframe: "10 săptămâni", category: "running" },
    { id: 12, title: "Parkrun Sub 20 min", description: "Aleargă un parkrun 5km sub 20 minute în 6 săptămâni.", difficulty: "hard", timeframe: "6 săptămâni", category: "running" },
    { id: 13, title: "50 Burpees Zilnic", description: "50 burpees în fiecare zi timp de 21 zile. Cardio + forță combinat.", difficulty: "medium", timeframe: "21 zile", category: "strength" },
    { id: 14, title: "6 Ore Somn Minim", description: "Dormi minim 6 ore calitative în fiecare noapte timp de 30 zile.", difficulty: "easy", timeframe: "30 zile", category: "recovery" },
    { id: 15, title: "Atingi 15% Body Fat", description: "Scade body fat la 15% în următoarele 16 săptămâni prin plan integrat.", difficulty: "hard", timeframe: "16 săptămâni", category: "nutrition" },
    { id: 16, title: "30 Zile Fără Alcool", description: "Zero alcool timp de 30 zile. Observă energia și focus-ul îmbunătățit.", difficulty: "medium", timeframe: "30 zile", category: "nutrition" },
    { id: 17, title: "Plank 5 Minute", description: "Ajunge să ții plank 5 minute continuu în 8 săptămâni.", difficulty: "hard", timeframe: "8 săptămâni", category: "strength" },
    { id: 18, title: "100km Lunar Running", description: "Aleargă 100km în fiecare lună timp de 6 luni consecutiv.", difficulty: "medium", timeframe: "6 luni", category: "running" },
    { id: 19, title: "20 Tracțiuni Consecutive", description: "Ajunge la 20 pull-ups consecutive cu formă perfectă în 12 săptămâni.", difficulty: "hard", timeframe: "12 săptămâni", category: "strength" },
    { id: 20, title: "Meditație Zilnică 10 Min", description: "10 minute meditație în fiecare dimineață timp de 60 zile.", difficulty: "easy", timeframe: "60 zile", category: "recovery" },
    { id: 21, title: "Alergare Matinală 30 Zile", description: "Aleargă în fiecare dimineață (minim 3km) timp de 30 zile consecutive.", difficulty: "medium", timeframe: "30 zile", category: "running" },
    { id: 22, title: "Squat 150kg", description: "Ajunge la back squat de 150kg în 20 săptămâni cu program structurat.", difficulty: "hard", timeframe: "20 săptămâni", category: "strength" },
    { id: 23, title: "Zero Fast Food 90 Zile", description: "Elimină complet fast food-ul timp de 90 zile. Meal prep săptămânal.", difficulty: "medium", timeframe: "90 zile", category: "nutrition" },
    { id: 24, title: "10km Sub 50 Min", description: "Aleargă 10km sub 50 minute în următoarele 10 săptămâni.", difficulty: "medium", timeframe: "10 săptămâni", category: "running" },
    { id: 25, title: "30 Zile Stretching", description: "15 minute stretching în fiecare seară timp de 30 zile.", difficulty: "easy", timeframe: "30 zile", category: "recovery" },
    { id: 26, title: "VO2 Max +10%", description: "Îmbunătățește VO2 max cu 10% în 12 săptămâni prin interval training.", difficulty: "hard", timeframe: "12 săptămâni", category: "running" },
    { id: 27, title: "1000km Anual Running", description: "Aleargă 1000km în acest an. Echivalent ~20km/săptămână.", difficulty: "hard", timeframe: "12 luni", category: "running" },
    { id: 28, title: "Bench Press 80kg", description: "Ajunge la bench press de 80kg în 16 săptămâni.", difficulty: "medium", timeframe: "16 săptămâni", category: "strength" },
    { id: 29, title: "2L Apă Zilnic", description: "Bea minim 2L apă zilnic timp de 60 zile. Hidratare optimă.", difficulty: "easy", timeframe: "60 zile", category: "nutrition" },
    { id: 30, title: "30 Zile Fără Cafea", description: "Zero cafea timp de 30 zile. Reset energiei naturale.", difficulty: "hard", timeframe: "30 zile", category: "nutrition" },
    { id: 31, title: "100 Flotări Continue", description: "Fă 100 flotări consecutive fără pauză în 10 săptămâni.", difficulty: "hard", timeframe: "10 săptămâni", category: "strength" },
    { id: 32, title: "5 Antrenamente/Săptămână", description: "5 antrenamente (3 running + 2 strength) săptămânal, 8 săptămâni.", difficulty: "hard", timeframe: "8 săptămâni", category: "habit" },
    { id: 33, title: "Sub 6 Min/km Pace", description: "Menține pace constant sub 6 min/km pe 5km în 8 săptămâni.", difficulty: "medium", timeframe: "8 săptămâni", category: "running" },
    { id: 34, title: "Box Jump 60cm", description: "Ajunge la box jump de 60cm înălțime în 12 săptămâni.", difficulty: "medium", timeframe: "12 săptămâni", category: "strength" },
    { id: 35, title: "Greutate Ideală", description: "Ajunge la greutatea ideală (BMI 22-24) în 16 săptămâni.", difficulty: "medium", timeframe: "16 săptămâni", category: "nutrition" },
    { id: 36, title: "30 Zile Paleo", description: "Dietă paleo strictă timp de 30 zile. Reset metabolic complet.", difficulty: "hard", timeframe: "30 zile", category: "nutrition" },
    { id: 37, title: "Handstand 30 Secunde", description: "Ține handstand liber 30 secunde în 16 săptămâni.", difficulty: "hard", timeframe: "16 săptămâni", category: "strength" },
    { id: 38, title: "21 Zile Trezire 6 AM", description: "Trezire la 6 AM în fiecare zi timp de 21 zile consecutive.", difficulty: "medium", timeframe: "21 zile", category: "habit" },
    { id: 39, title: "15km Lung Run", description: "Finalizează un long run de 15km în 10 săptămâni (începând de la 5km).", difficulty: "medium", timeframe: "10 săptămâni", category: "running" },
    { id: 40, title: "30 Minute Plank Total", description: "Acumulează 30 minute plank total într-o sesiune în 12 săptămâni.", difficulty: "hard", timeframe: "12 săptămâni", category: "strength" },
    { id: 41, title: "Zero Zahăr Rafinat", description: "Elimină zahărul rafinat complet timp de 90 zile.", difficulty: "hard", timeframe: "90 zile", category: "nutrition" },
    { id: 42, title: "Interval Training 2x/Săpt", description: "2 sesiuni interval training săptămânal timp de 12 săptămâni.", difficulty: "medium", timeframe: "12 săptămâni", category: "running" },
    { id: 43, title: "50 Tracțiuni Total", description: "Fă 50 pull-ups total (in sets) în fiecare zi timp de 21 zile.", difficulty: "hard", timeframe: "21 zile", category: "strength" },
    { id: 44, title: "Resting HR Sub 60", description: "Scade resting heart rate sub 60 bpm în 16 săptămâni.", difficulty: "medium", timeframe: "16 săptămâni", category: "running" },
    { id: 45, title: "Meal Prep Duminici", description: "Meal prep pentru toată săptămâna în fiecare duminică, 12 săptămâni.", difficulty: "medium", timeframe: "12 săptămâni", category: "nutrition" },
    { id: 46, title: "Yoga 3x/Săptămână", description: "3 sesiuni yoga săptămânal timp de 8 săptămâni pentru flexibilitate.", difficulty: "easy", timeframe: "8 săptămâni", category: "recovery" },
    { id: 47, title: "30 Zile Cold Showers", description: "Duș rece în fiecare dimineață timp de 30 zile. Recovery boost.", difficulty: "hard", timeframe: "30 zile", category: "recovery" },
    { id: 48, title: "Pistol Squat 10 Reps", description: "Ajunge la 10 pistol squats pe fiecare picior în 12 săptămâni.", difficulty: "hard", timeframe: "12 săptămâni", category: "strength" },
    { id: 49, title: "5 Porții Legume Zilnic", description: "Mănâncă minim 5 porții legume zilnic timp de 60 zile.", difficulty: "medium", timeframe: "60 zile", category: "nutrition" },
    { id: 50, title: "Fără Screen 1h Pre-Somn", description: "Zero screen time cu 1h înainte de culcare timp de 30 zile.", difficulty: "medium", timeframe: "30 zile", category: "recovery" },
    { id: 51, title: "40 Push-ups Neîntrerupt", description: "Fă 40 push-ups consecutive perfecte în 8 săptămâni.", difficulty: "medium", timeframe: "8 săptămâni", category: "strength" },
    { id: 52, title: "5km Parkrun Săptămânal", description: "Participă la parkrun 5km în fiecare sâmbătă timp de 12 săptămâni.", difficulty: "easy", timeframe: "12 săptămâni", category: "running" },
    { id: 53, title: "Intermittent Fasting 16/8", description: "16/8 intermittent fasting zilnic timp de 60 zile.", difficulty: "medium", timeframe: "60 zile", category: "nutrition" },
    { id: 54, title: "Turkish Get-Up 32kg", description: "Execută turkish get-up cu kettlebell 32kg în 16 săptămâni.", difficulty: "hard", timeframe: "16 săptămâni", category: "strength" },
    { id: 55, title: "1 Minut Wall Sit", description: "Ține wall sit 1 minut continuu în 6 săptămâni.", difficulty: "medium", timeframe: "6 săptămâni", category: "strength" }
  ],
  en: [
    { id: 1, title: "10km Tomorrow", description: "Run 10km at comfortable pace tomorrow morning. Finish between 60-75 min.", difficulty: "medium", timeframe: "1 day", category: "running" },
    { id: 2, title: "Half-Marathon in 6 Months", description: "Train for a half-marathon (21.1km) in next 6 months. Target: under 2h 15min.", difficulty: "hard", timeframe: "6 months", category: "running" },
    { id: 3, title: "100 Push-ups Daily", description: "Do 100 push-ups per day for 30 days. Can split into sets of 20-25.", difficulty: "medium", timeframe: "30 days", category: "strength" },
    { id: 4, title: "5km Under 25 min", description: "Hit a 5km under 25 minutes in next 8 weeks.", difficulty: "medium", timeframe: "8 weeks", category: "running" },
    { id: 5, title: "Marathon in 12 Months", description: "Full marathon prep (42.2km). Target: finish under 4h 30min.", difficulty: "hard", timeframe: "12 months", category: "running" },
    { id: 6, title: "Lose 5kg in 90 Days", description: "Drop 5kg body fat through running, strength and optimized nutrition.", difficulty: "medium", timeframe: "90 days", category: "nutrition" },
    { id: 7, title: "30 Days Sugar-Free", description: "Eliminate all added sugar for 30 days. Sustained energy guaranteed.", difficulty: "medium", timeframe: "30 days", category: "nutrition" },
    { id: 8, title: "3 Workouts/Week", description: "Maintain consistency: 3 workouts (2 running + 1 strength) weekly, 12 weeks.", difficulty: "easy", timeframe: "12 weeks", category: "habit" },
    { id: 9, title: "Deadlift 100kg", description: "Hit 100kg deadlift with perfect form in 16 weeks.", difficulty: "hard", timeframe: "16 weeks", category: "strength" },
    { id: 10, title: "10,000 Steps Daily", description: "10,000 steps every day for 60 days. Use lunch breaks.", difficulty: "easy", timeframe: "60 days", category: "movement" },
    { id: 11, title: "15km Trail Run", description: "Complete a 15km mountain trail run in next 10 weeks.", difficulty: "hard", timeframe: "10 weeks", category: "running" },
    { id: 12, title: "Parkrun Under 20 min", description: "Run a parkrun 5km under 20 minutes in 6 weeks.", difficulty: "hard", timeframe: "6 weeks", category: "running" },
    { id: 13, title: "50 Burpees Daily", description: "50 burpees every day for 21 days. Cardio + strength combined.", difficulty: "medium", timeframe: "21 days", category: "strength" },
    { id: 14, title: "6 Hours Sleep Minimum", description: "Sleep minimum 6 quality hours every night for 30 days.", difficulty: "easy", timeframe: "30 days", category: "recovery" },
    { id: 15, title: "Hit 15% Body Fat", description: "Drop body fat to 15% in next 16 weeks through integrated plan.", difficulty: "hard", timeframe: "16 weeks", category: "nutrition" },
    { id: 16, title: "30 Days Alcohol-Free", description: "Zero alcohol for 30 days. Notice improved energy and focus.", difficulty: "medium", timeframe: "30 days", category: "nutrition" },
    { id: 17, title: "5-Minute Plank", description: "Hold plank for 5 minutes continuously in 8 weeks.", difficulty: "hard", timeframe: "8 weeks", category: "strength" },
    { id: 18, title: "100km Monthly Running", description: "Run 100km every month for 6 consecutive months.", difficulty: "medium", timeframe: "6 months", category: "running" },
    { id: 19, title: "20 Consecutive Pull-ups", description: "Hit 20 consecutive pull-ups with perfect form in 12 weeks.", difficulty: "hard", timeframe: "12 weeks", category: "strength" },
    { id: 20, title: "Daily 10min Meditation", description: "10 minutes meditation every morning for 60 days.", difficulty: "easy", timeframe: "60 days", category: "recovery" },
    { id: 21, title: "30-Day Morning Runs", description: "Run every morning (minimum 3km) for 30 consecutive days.", difficulty: "medium", timeframe: "30 days", category: "running" },
    { id: 22, title: "Squat 150kg", description: "Hit 150kg back squat in 20 weeks with structured program.", difficulty: "hard", timeframe: "20 weeks", category: "strength" },
    { id: 23, title: "Zero Fast Food 90 Days", description: "Eliminate all fast food for 90 days. Weekly meal prep.", difficulty: "medium", timeframe: "90 days", category: "nutrition" },
    { id: 24, title: "10km Under 50 Min", description: "Run 10km under 50 minutes in next 10 weeks.", difficulty: "medium", timeframe: "10 weeks", category: "running" },
    { id: 25, title: "30 Days Stretching", description: "15 minutes stretching every evening for 30 days.", difficulty: "easy", timeframe: "30 days", category: "recovery" },
    { id: 26, title: "VO2 Max +10%", description: "Improve VO2 max by 10% in 12 weeks through interval training.", difficulty: "hard", timeframe: "12 weeks", category: "running" },
    { id: 27, title: "1000km Yearly Running", description: "Run 1000km this year. Equivalent to ~20km/week.", difficulty: "hard", timeframe: "12 months", category: "running" },
    { id: 28, title: "Bench Press 80kg", description: "Hit 80kg bench press in 16 weeks.", difficulty: "medium", timeframe: "16 weeks", category: "strength" },
    { id: 29, title: "2L Water Daily", description: "Drink minimum 2L water daily for 60 days. Optimal hydration.", difficulty: "easy", timeframe: "60 days", category: "nutrition" },
    { id: 30, title: "30 Days Caffeine-Free", description: "Zero caffeine for 30 days. Natural energy reset.", difficulty: "hard", timeframe: "30 days", category: "nutrition" },
    { id: 31, title: "100 Continuous Push-ups", description: "Do 100 push-ups consecutively without pause in 10 weeks.", difficulty: "hard", timeframe: "10 weeks", category: "strength" },
    { id: 32, title: "5 Workouts/Week", description: "5 workouts (3 running + 2 strength) weekly, 8 weeks.", difficulty: "hard", timeframe: "8 weeks", category: "habit" },
    { id: 33, title: "Under 6 Min/km Pace", description: "Maintain constant pace under 6 min/km on 5km in 8 weeks.", difficulty: "medium", timeframe: "8 weeks", category: "running" },
    { id: 34, title: "60cm Box Jump", description: "Hit 60cm height box jump in 12 weeks.", difficulty: "medium", timeframe: "12 weeks", category: "strength" },
    { id: 35, title: "Ideal Weight", description: "Reach ideal weight (BMI 22-24) in 16 weeks.", difficulty: "medium", timeframe: "16 weeks", category: "nutrition" },
    { id: 36, title: "30 Days Paleo", description: "Strict paleo diet for 30 days. Complete metabolic reset.", difficulty: "hard", timeframe: "30 days", category: "nutrition" },
    { id: 37, title: "30-Second Handstand", description: "Hold freestanding handstand 30 seconds in 16 weeks.", difficulty: "hard", timeframe: "16 weeks", category: "strength" },
    { id: 38, title: "21 Days 6 AM Wake-up", description: "Wake up at 6 AM every day for 21 consecutive days.", difficulty: "medium", timeframe: "21 days", category: "habit" },
    { id: 39, title: "15km Long Run", description: "Complete a 15km long run in 10 weeks (starting from 5km).", difficulty: "medium", timeframe: "10 weeks", category: "running" },
    { id: 40, title: "30 Minutes Total Plank", description: "Accumulate 30 minutes total plank in one session in 12 weeks.", difficulty: "hard", timeframe: "12 weeks", category: "strength" },
    { id: 41, title: "Zero Refined Sugar", description: "Eliminate refined sugar completely for 90 days.", difficulty: "hard", timeframe: "90 days", category: "nutrition" },
    { id: 42, title: "Interval Training 2x/Week", description: "2 interval training sessions weekly for 12 weeks.", difficulty: "medium", timeframe: "12 weeks", category: "running" },
    { id: 43, title: "50 Total Pull-ups", description: "Do 50 total pull-ups (in sets) every day for 21 days.", difficulty: "hard", timeframe: "21 days", category: "strength" },
    { id: 44, title: "Resting HR Under 60", description: "Lower resting heart rate under 60 bpm in 16 weeks.", difficulty: "medium", timeframe: "16 weeks", category: "running" },
    { id: 45, title: "Sunday Meal Prep", description: "Meal prep entire week every Sunday for 12 weeks.", difficulty: "medium", timeframe: "12 weeks", category: "nutrition" },
    { id: 46, title: "Yoga 3x/Week", description: "3 yoga sessions weekly for 8 weeks for flexibility.", difficulty: "easy", timeframe: "8 weeks", category: "recovery" },
    { id: 47, title: "30 Days Cold Showers", description: "Cold shower every morning for 30 days. Recovery boost.", difficulty: "hard", timeframe: "30 days", category: "recovery" },
    { id: 48, title: "Pistol Squat 10 Reps", description: "Hit 10 pistol squats on each leg in 12 weeks.", difficulty: "hard", timeframe: "12 weeks", category: "strength" },
    { id: 49, title: "5 Veggie Servings Daily", description: "Eat minimum 5 vegetable servings daily for 60 days.", difficulty: "medium", timeframe: "60 days", category: "nutrition" },
    { id: 50, title: "No Screen 1h Pre-Sleep", description: "Zero screen time 1h before bed for 30 days.", difficulty: "medium", timeframe: "30 days", category: "recovery" },
    { id: 51, title: "40 Unbroken Push-ups", description: "Do 40 consecutive perfect push-ups in 8 weeks.", difficulty: "medium", timeframe: "8 weeks", category: "strength" },
    { id: 52, title: "Weekly 5km Parkrun", description: "Attend 5km parkrun every Saturday for 12 weeks.", difficulty: "easy", timeframe: "12 weeks", category: "running" },
    { id: 53, title: "Intermittent Fasting 16/8", description: "16/8 intermittent fasting daily for 60 days.", difficulty: "medium", timeframe: "60 days", category: "nutrition" },
    { id: 54, title: "Turkish Get-Up 32kg", description: "Execute turkish get-up with 32kg kettlebell in 16 weeks.", difficulty: "hard", timeframe: "16 weeks", category: "strength" },
    { id: 55, title: "1-Minute Wall Sit", description: "Hold wall sit for 1 minute continuously in 6 weeks.", difficulty: "medium", timeframe: "6 weeks", category: "strength" }
  ],
  fr: [
    { id: 1, title: "10km Demain", description: "Courez 10km à un rythme confortable demain matin. Terminez entre 60-75 min.", difficulty: "medium", timeframe: "1 jour", category: "running" },
    { id: 2, title: "Semi-Marathon en 6 Mois", description: "Entraînez-vous pour un semi-marathon (21.1km) dans les 6 prochains mois. Objectif: moins de 2h 15min.", difficulty: "hard", timeframe: "6 mois", category: "running" },
    { id: 3, title: "100 Pompes Quotidiennes", description: "Faites 100 pompes par jour pendant 30 jours. Divisez en séries de 20-25.", difficulty: "medium", timeframe: "30 jours", category: "strength" },
    { id: 4, title: "5km Sous 25 min", description: "Atteignez un 5km sous 25 minutes dans les 8 prochaines semaines.", difficulty: "medium", timeframe: "8 semaines", category: "running" },
    { id: 5, title: "Marathon en 12 Mois", description: "Préparation marathon complète (42.2km). Objectif: finir sous 4h 30min.", difficulty: "hard", timeframe: "12 mois", category: "running" },
    { id: 6, title: "Perdre 5kg en 90 Jours", description: "Perdez 5kg de graisse corporelle via course, force et nutrition optimisée.", difficulty: "medium", timeframe: "90 jours", category: "nutrition" },
    { id: 7, title: "30 Jours Sans Sucre", description: "Éliminez tout sucre ajouté pendant 30 jours. Énergie soutenue garantie.", difficulty: "medium", timeframe: "30 jours", category: "nutrition" },
    { id: 8, title: "3 Entraînements/Semaine", description: "Maintenez la cohérence: 3 entraînements (2 course + 1 force) hebdomadaires, 12 semaines.", difficulty: "easy", timeframe: "12 semaines", category: "habit" },
    { id: 9, title: "Soulevé de Terre 100kg", description: "Atteignez 100kg soulevé de terre avec forme parfaite en 16 semaines.", difficulty: "hard", timeframe: "16 semaines", category: "strength" },
    { id: 10, title: "10 000 Pas Quotidiens", description: "10 000 pas chaque jour pendant 60 jours. Utilisez les pauses déjeuner.", difficulty: "easy", timeframe: "60 jours", category: "movement" },
    { id: 11, title: "Trail Run 15km", description: "Complétez un trail run de 15km en montagne dans les 10 prochaines semaines.", difficulty: "hard", timeframe: "10 semaines", category: "running" },
    { id: 12, title: "Parkrun Sous 20 min", description: "Courez un parkrun 5km sous 20 minutes en 6 semaines.", difficulty: "hard", timeframe: "6 semaines", category: "running" },
    { id: 13, title: "50 Burpees Quotidiens", description: "50 burpees chaque jour pendant 21 jours. Cardio + force combinés.", difficulty: "medium", timeframe: "21 jours", category: "strength" },
    { id: 14, title: "6 Heures Sommeil Minimum", description: "Dormez minimum 6 heures de qualité chaque nuit pendant 30 jours.", difficulty: "easy", timeframe: "30 jours", category: "recovery" },
    { id: 15, title: "Atteindre 15% Masse Grasse", description: "Réduisez masse grasse à 15% en 16 semaines via plan intégré.", difficulty: "hard", timeframe: "16 semaines", category: "nutrition" },
    { id: 16, title: "30 Jours Sans Alcool", description: "Zéro alcool pendant 30 jours. Remarquez énergie et focus améliorés.", difficulty: "medium", timeframe: "30 jours", category: "nutrition" },
    { id: 17, title: "Planche 5 Minutes", description: "Tenez la planche 5 minutes en continu en 8 semaines.", difficulty: "hard", timeframe: "8 semaines", category: "strength" },
    { id: 18, title: "100km Course Mensuelle", description: "Courez 100km chaque mois pendant 6 mois consécutifs.", difficulty: "medium", timeframe: "6 mois", category: "running" },
    { id: 19, title: "20 Tractions Consécutives", description: "Atteignez 20 tractions consécutives avec forme parfaite en 12 semaines.", difficulty: "hard", timeframe: "12 semaines", category: "strength" },
    { id: 20, title: "Méditation 10min Quotidienne", description: "10 minutes méditation chaque matin pendant 60 jours.", difficulty: "easy", timeframe: "60 jours", category: "recovery" },
    { id: 21, title: "30 Jours Course Matinale", description: "Courez chaque matin (minimum 3km) pendant 30 jours consécutifs.", difficulty: "medium", timeframe: "30 jours", category: "running" },
    { id: 22, title: "Squat 150kg", description: "Atteignez 150kg squat dos en 20 semaines avec programme structuré.", difficulty: "hard", timeframe: "20 semaines", category: "strength" },
    { id: 23, title: "Zéro Fast Food 90 Jours", description: "Éliminez tout fast food pendant 90 jours. Meal prep hebdomadaire.", difficulty: "medium", timeframe: "90 jours", category: "nutrition" },
    { id: 24, title: "10km Sous 50 Min", description: "Courez 10km sous 50 minutes dans les 10 prochaines semaines.", difficulty: "medium", timeframe: "10 semaines", category: "running" },
    { id: 25, title: "30 Jours Étirements", description: "15 minutes d'étirements chaque soir pendant 30 jours.", difficulty: "easy", timeframe: "30 jours", category: "recovery" },
    { id: 26, title: "VO2 Max +10%", description: "Améliorez VO2 max de 10% en 12 semaines via interval training.", difficulty: "hard", timeframe: "12 semaines", category: "running" },
    { id: 27, title: "1000km Course Annuelle", description: "Courez 1000km cette année. Équivalent à ~20km/semaine.", difficulty: "hard", timeframe: "12 mois", category: "running" },
    { id: 28, title: "Développé Couché 80kg", description: "Atteignez 80kg développé couché en 16 semaines.", difficulty: "medium", timeframe: "16 semaines", category: "strength" },
    { id: 29, title: "2L Eau Quotidienne", description: "Buvez minimum 2L eau par jour pendant 60 jours. Hydratation optimale.", difficulty: "easy", timeframe: "60 jours", category: "nutrition" },
    { id: 30, title: "30 Jours Sans Caféine", description: "Zéro caféine pendant 30 jours. Reset énergie naturelle.", difficulty: "hard", timeframe: "30 jours", category: "nutrition" },
    { id: 31, title: "100 Pompes Continues", description: "Faites 100 pompes consécutives sans pause en 10 semaines.", difficulty: "hard", timeframe: "10 semaines", category: "strength" },
    { id: 32, title: "5 Entraînements/Semaine", description: "5 entraînements (3 course + 2 force) hebdomadaires, 8 semaines.", difficulty: "hard", timeframe: "8 semaines", category: "habit" },
    { id: 33, title: "Sous 6 Min/km Rythme", description: "Maintenez rythme constant sous 6 min/km sur 5km en 8 semaines.", difficulty: "medium", timeframe: "8 semaines", category: "running" },
    { id: 34, title: "Box Jump 60cm", description: "Atteignez box jump de 60cm hauteur en 12 semaines.", difficulty: "medium", timeframe: "12 semaines", category: "strength" },
    { id: 35, title: "Poids Idéal", description: "Atteignez poids idéal (IMC 22-24) en 16 semaines.", difficulty: "medium", timeframe: "16 semaines", category: "nutrition" },
    { id: 36, title: "30 Jours Paléo", description: "Régime paléo strict pendant 30 jours. Reset métabolique complet.", difficulty: "hard", timeframe: "30 jours", category: "nutrition" },
    { id: 37, title: "Équilibre Main 30 Secondes", description: "Tenez équilibre sur mains libre 30 secondes en 16 semaines.", difficulty: "hard", timeframe: "16 semaines", category: "strength" },
    { id: 38, title: "21 Jours Réveil 6h", description: "Réveil à 6h chaque jour pendant 21 jours consécutifs.", difficulty: "medium", timeframe: "21 jours", category: "habit" },
    { id: 39, title: "15km Longue Course", description: "Complétez une longue course de 15km en 10 semaines (départ 5km).", difficulty: "medium", timeframe: "10 semaines", category: "running" },
    { id: 40, title: "30 Minutes Planche Total", description: "Accumulez 30 minutes planche total en une session en 12 semaines.", difficulty: "hard", timeframe: "12 semaines", category: "strength" },
    { id: 41, title: "Zéro Sucre Raffiné", description: "Éliminez sucre raffiné complètement pendant 90 jours.", difficulty: "hard", timeframe: "90 jours", category: "nutrition" },
    { id: 42, title: "Interval Training 2x/Semaine", description: "2 sessions interval training hebdomadaires pendant 12 semaines.", difficulty: "medium", timeframe: "12 semaines", category: "running" },
    { id: 43, title: "50 Tractions Total", description: "Faites 50 tractions total (en séries) chaque jour pendant 21 jours.", difficulty: "hard", timeframe: "21 jours", category: "strength" },
    { id: 44, title: "FC Repos Sous 60", description: "Réduisez fréquence cardiaque repos sous 60 bpm en 16 semaines.", difficulty: "medium", timeframe: "16 semaines", category: "running" },
    { id: 45, title: "Meal Prep Dimanche", description: "Meal prep semaine entière chaque dimanche pendant 12 semaines.", difficulty: "medium", timeframe: "12 semaines", category: "nutrition" },
    { id: 46, title: "Yoga 3x/Semaine", description: "3 sessions yoga hebdomadaires pendant 8 semaines pour flexibilité.", difficulty: "easy", timeframe: "8 semaines", category: "recovery" },
    { id: 47, title: "30 Jours Douches Froides", description: "Douche froide chaque matin pendant 30 jours. Boost récupération.", difficulty: "hard", timeframe: "30 jours", category: "recovery" },
    { id: 48, title: "Pistol Squat 10 Reps", description: "Atteignez 10 pistol squats sur chaque jambe en 12 semaines.", difficulty: "hard", timeframe: "12 semaines", category: "strength" },
    { id: 49, title: "5 Portions Légumes Quotidiennes", description: "Mangez minimum 5 portions légumes quotidiennement pendant 60 jours.", difficulty: "medium", timeframe: "60 jours", category: "nutrition" },
    { id: 50, title: "Pas Écran 1h Pré-Sommeil", description: "Zéro écran 1h avant coucher pendant 30 jours.", difficulty: "medium", timeframe: "30 jours", category: "recovery" },
    { id: 51, title: "40 Pompes Ininterrompues", description: "Faites 40 pompes consécutives parfaites en 8 semaines.", difficulty: "medium", timeframe: "8 semaines", category: "strength" },
    { id: 52, title: "Parkrun 5km Hebdomadaire", description: "Participez au parkrun 5km chaque samedi pendant 12 semaines.", difficulty: "easy", timeframe: "12 semaines", category: "running" },
    { id: 53, title: "Jeûne Intermittent 16/8", description: "Jeûne intermittent 16/8 quotidien pendant 60 jours.", difficulty: "medium", timeframe: "60 jours", category: "nutrition" },
    { id: 54, title: "Turkish Get-Up 32kg", description: "Exécutez turkish get-up avec kettlebell 32kg en 16 semaines.", difficulty: "hard", timeframe: "16 semaines", category: "strength" },
    { id: 55, title: "1 Minute Chaise Murale", description: "Tenez chaise murale 1 minute en continu en 6 semaines.", difficulty: "medium", timeframe: "6 semaines", category: "strength" }
  ]
};

export const getRandomChallenge = (lang = 'ro') => {
  const langChallenges = challenges[lang] || challenges.ro;
  const randomIndex = Math.floor(Math.random() * langChallenges.length);
  return langChallenges[randomIndex];
};